"""Versioned Pydantic contracts — the structural source of truth."""

from .base import (
    CONTRACTS_VERSION,
    HASH_PATTERN,
    PROBABILITY_TOLERANCE,
    SCHEMA_BASE,
    SourceMode,
    require_probability_sum,
)
from .council import (
    AgentChallenge,
    AgentClaim,
    AgentRole,
    AgreementSummary,
    AnalysisStep,
    CouncilCallRecord,
    CouncilCycleDetail,
    CouncilResult,
    CouncilUsageSummary,
    PolicyRejection,
    Provenance,
    ProviderHealth,
    ReadingLayer,
    SystematicReading,
)
from .events import WebSocketEnvelope, WsEventType
from .evidence import (
    CalibrationSummary,
    EvidencePacket,
    EvidenceValue,
    QualitySummary,
    TopologySummary,
    WindowSummary,
)
from .frames import CsiQuality, NormalizedCsiFrame, SourceManifest
from .health import SourceHealth
from .registry import CONTRACT_SCHEMAS, schema_for
from .signals import (
    DepthProbabilities,
    DepthZone,
    FeatureWindow,
    LinkFeatures,
    MotionSignal,
    OccupancyDensity,
    OccupancyProbabilities,
    PairedFeatures,
    SignalTriplet,
    WindowQuality,
)

__all__ = [
    "CONTRACTS_VERSION",
    "CONTRACT_SCHEMAS",
    "HASH_PATTERN",
    "PROBABILITY_TOLERANCE",
    "SCHEMA_BASE",
    "AgentChallenge",
    "AgentClaim",
    "AgentRole",
    "AgreementSummary",
    "AnalysisStep",
    "CalibrationSummary",
    "CouncilCallRecord",
    "CouncilCycleDetail",
    "CouncilResult",
    "CouncilUsageSummary",
    "CsiQuality",
    "DepthProbabilities",
    "DepthZone",
    "EvidencePacket",
    "EvidenceValue",
    "FeatureWindow",
    "LinkFeatures",
    "MotionSignal",
    "NormalizedCsiFrame",
    "OccupancyDensity",
    "OccupancyProbabilities",
    "PairedFeatures",
    "PolicyRejection",
    "Provenance",
    "ProviderHealth",
    "QualitySummary",
    "ReadingLayer",
    "SignalTriplet",
    "SourceHealth",
    "SourceManifest",
    "SourceMode",
    "SystematicReading",
    "TopologySummary",
    "WebSocketEnvelope",
    "WindowQuality",
    "WindowSummary",
    "WsEventType",
    "require_probability_sum",
    "schema_for",
]
