"""Reference wire-protocol codec shared by firmware, collector, and tests."""

from .wire_protocol import (
    CSI_MAX_LEN,
    FRAME_MAX_LEN,
    FRAME_TYPE_DATA,
    FRAME_TYPE_STATUS,
    HEADER_LEN,
    MAGIC_U32,
    PROTOCOL_VERSION,
    STATUS_PAYLOAD_LEN,
    TX_PAYLOAD_LEN,
    TX_PAYLOAD_MAGIC,
    FrameParser,
    ParsedFrame,
    StatusPayload,
    WireHeader,
    crc32,
    encode_data_frame,
    encode_header,
    encode_status_frame,
    encode_tx_payload,
    parse_status_payload,
    parse_tx_payload,
    seq_gap,
)

__all__ = [
    "CSI_MAX_LEN",
    "FRAME_MAX_LEN",
    "FRAME_TYPE_DATA",
    "FRAME_TYPE_STATUS",
    "HEADER_LEN",
    "MAGIC_U32",
    "PROTOCOL_VERSION",
    "STATUS_PAYLOAD_LEN",
    "TX_PAYLOAD_LEN",
    "TX_PAYLOAD_MAGIC",
    "FrameParser",
    "ParsedFrame",
    "StatusPayload",
    "WireHeader",
    "crc32",
    "encode_data_frame",
    "encode_header",
    "encode_status_frame",
    "encode_tx_payload",
    "parse_status_payload",
    "parse_tx_payload",
    "seq_gap",
]
